Repository andela/ah-the-immortals-backend, pull requests merged in 2019-05, with the labels that each got.

#13 #165305754 Add descriptive signup validation errors
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_validations.py
Labels: finished

#16 #165305758 User profiles(Users)
  .coveragerc
  .env-example
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/profiles/migrations/__init__.py
  authors/apps/profiles/models.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/__init__.py
  authors/apps/profiles/tests/basetests.py
  authors/apps/profiles/tests/test_profiles.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  authors/settings.py
  authors/urls.py
  requirements.txt
Labels: finished

#17 #165305757 Enable Social login via Google, Facebook and Twitter
  .env-example
  README.md
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/basetests.py
  authors/apps/authentication/tests/test_social_auth.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/settings.py
  requirements.txt
Labels: reviews required

#12 #165305756 Password Reset (Authentication)
  .env-example
  README.md
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/basetests.py
  authors/apps/authentication/tests/test_password_reset.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/settings.py
  authors/templates/password_reset.html
  authors/utils/__init__.py
  authors/utils/mailer.py
Labels: finished

#18 #165305763 Users should be able to follow each other
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/profiles/models.py
  authors/apps/profiles/renderers.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/test_follow.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  authors/urls.py
  requirements.txt
Labels: finished

#19 #165305766 List users functionality
  .env-example
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/basetests.py
  authors/apps/profiles/tests/test_profiles.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  requirements.txt
Labels: reviews required

#20 #165305755 An email should be sent on success-full signup and user gets verified
  .env-example
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/models.py
  authors/apps/authentication/renderers.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/basetests.py
  authors/apps/authentication/tests/test_jwt_authentication.py
  authors/apps/authentication/tests/test_users.py
  authors/apps/authentication/tests/test_verify_user.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/basetests.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  authors/apps/utils/__init__.py
  authors/apps/utils/mailer.py
  authors/settings.py
  authors/templates/mail.html
  authors/urls.py
  requirements.txt
Labels: finished

#21 #165305753 Fix error messages on login
  .coveragerc
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_users.py
Labels: reviews required

#23 #165305756 Fix Password Reset Feature
  .env-example
  authors/apps/authentication/renderers.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/basetests.py
  authors/apps/authentication/tests/test_password_reset.py
  authors/apps/authentication/views.py
  authors/settings.py
  authors/templates/password_reset.html
  authors/utils/mailer.py
  requirements.txt
Labels: finished

#25 #165305758 Fix profiles feature
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/basetests.py
  authors/apps/profiles/tests/test_profiles.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
Labels: finished

#26 #165305757 Fix Error Messages in Social Login Feature
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_social_auth.py
  authors/apps/authentication/views.py
Labels: reviews required

#30 #165812170 Integrate code climate to GitHub
  .codeclimate.yml
  README.md
Labels: finished

#29 #165812173 Redirect application root URL to swagger documentation
  authors/urls.py
Labels: finished

#35 #165812173 Redirect app root to Swagger
  authors/urls.py
Labels: finished

#37 #165305766 Fixes user profile fields
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/test_profiles.py
  authors/apps/profiles/views.py
Labels: finished

#34 #165305754 Fix validations errors on signup
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/basetests.py
  authors/apps/authentication/tests/test_jwt_authentication.py
  authors/apps/authentication/tests/test_users.py
  authors/apps/authentication/tests/test_validations.py
Labels: finished

#31 165305755 Allow non-verified user to access get request
  authors/apps/authentication/backends.py
  authors/apps/authentication/renderers.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/basetests.py
  authors/apps/authentication/tests/test_jwt_authentication.py
  authors/apps/authentication/tests/test_verify_user.py
  authors/apps/authentication/views.py
  authors/apps/profiles/tests/test_follow.py
  authors/apps/profiles/views.py
  authors/templates/mail.html
Labels: finished

#27 #165305763 fix following/unfollow/get followers/get following status messages
  authors/apps/profiles/exceptions.py
  authors/apps/profiles/migrations/0002_profile_following.py
  authors/apps/profiles/migrations/0003_auto_20190507_1614.py
  authors/apps/profiles/models.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests/test_follow.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
Labels: finished

#32 #165305752 Update swagger description messages
  authors/apps/authentication/tests/basetests.py
  authors/apps/authentication/tests/test_password_reset.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/profiles/tests/basetests.py
Labels: finished

#36 #165835216 Validate Password During Password Reset
  README.md
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_password_reset.py
  authors/apps/authentication/tests/test_validations.py
  authors/apps/authentication/views.py
  authors/apps/profiles/urls.py
  authors/utils/password_validators.py
Labels: finished

#33 #165305759 Create Articles CRUD
  README.md
  authors/apps/articles/__init__.py
  authors/apps/articles/admin.py
  authors/apps/articles/exceptions.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0002_auto_20190506_2154.py
  authors/apps/articles/migrations/0003_auto_20190507_0737.py
  authors/apps/articles/migrations/__init__.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/__init__.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_articles.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/profiles/migrations/0004_delete_followers.py
  authors/settings.py
  authors/urls.py
  requirements.txt
Labels: reviews required

#43 #165305767 Add Tags to Articles
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0002_auto_20190506_2154.py
  authors/apps/articles/migrations/0003_auto_20190507_0737.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_articles.py
  authors/apps/articles/tests/test_tags.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
Labels: reviews required

#40 #165305768 Add Pagination to Articles
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_articles.py
  authors/apps/articles/tests/test_pagination.py
  authors/apps/articles/tests/test_tags.py
  authors/apps/articles/views.py
Labels: finished

#49 #165913407 Remove unused tags from the database and Handle page limit errors
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_pagination.py
  authors/apps/articles/views.py
Labels: finished

#47 #165305762 Liking and Disliking articles
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_like_dislike.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/profiles/serializers.py
  authors/apps/utils/baseserializer.py
  authors/settings.py
  requirements.txt
Labels: finished

#41 #165305764 Favoriting an article
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_favorite.py
  authors/apps/articles/tests/test_like_dislike.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
Labels: finished

#44 #165305760 Users can rate articles
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0002_auto_20190510_0825.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_ratings.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/views.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/profiles/migrations/0002_profile_following.py
  authors/apps/profiles/migrations/0003_auto_20190507_1614.py
  authors/apps/profiles/migrations/0004_delete_followers.py
Labels: feedback implemented, reviews required

#50 #165305761 Users can comment on articles
  authors/apps/articles/exceptions.py
  authors/apps/articles/migrations/0002_comment.py
  authors/apps/articles/migrations/0003_merge_20190510_0946.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_comments.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/profiles/models.py
Labels: reviews required

#45 #165305765 Implement user notifications
  authors/apps/appnotifications/__init__.py
  authors/apps/appnotifications/admin.py
  authors/apps/appnotifications/migrations/0001_initial.py
  authors/apps/appnotifications/migrations/0002_usernotification_user.py
  authors/apps/appnotifications/migrations/__init__.py
  authors/apps/appnotifications/models.py
  authors/apps/appnotifications/serializers.py
  authors/apps/appnotifications/tests/__init__.py
  authors/apps/appnotifications/tests/basetest.py
  authors/apps/appnotifications/tests/test_notifications.py
  authors/apps/appnotifications/urls.py
  authors/apps/appnotifications/views.py
  authors/apps/articles/apps.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0002_auto_20190510_1013.py
  authors/apps/articles/migrations/0002_comment.py
  authors/apps/articles/migrations/0003_merge_20190510_0946.py
  authors/apps/articles/models.py
  authors/apps/articles/renderers.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_favorite.py
  authors/apps/articles/tests/test_like_dislike.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/views.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/urls.py
  authors/apps/utils/mailer.py
  authors/settings.py
  authors/templates/notification_template.html
  authors/urls.py
  authors/utils/actions.py
  authors/utils/baseserializer.py
  authors/utils/mailer.py
  authors/utils/notification_handlers.py
  requirements.txt
Labels: reviews required

#46 #165305769 Add Custom search filters
  .gitignore
  authors/apps/articles/apps.py
  authors/apps/articles/filters.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0002_auto_20190510_1013.py
  authors/apps/articles/renderers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_filters.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/urls.py
  authors/settings.py
  requirements.txt
Labels: reviews required

#52 #165940869 Add number of articles per page
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_pagination.py
Labels: finished

#56 165962764-bg(Fix search)fix-search-error-messages
  authors/apps/articles/tests/test_filters.py
  authors/apps/articles/views.py
Labels: reviews required

#53 #165952876 Fix subscriptions
  authors/apps/appnotifications/tests/test_notifications.py
  authors/apps/appnotifications/views.py
  authors/utils/notification_handlers.py
Labels: finished

#54 #165952635 Fix Comment on articles
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_comments.py
  authors/apps/articles/utils.py
  authors/apps/articles/views.py
Labels: finished

#55 #165951620 Fix favoriting an article
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_favorite.py
  authors/apps/articles/tests/test_like_dislike.py
  authors/apps/articles/tests/test_ratings.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
Labels: finished

#57 #165962764 Fix-search-error-messages
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_filters.py
  authors/apps/articles/views.py
Labels: finished

#60 #165305770 Add Read-Time For an Article
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_article_read_time.py
  authors/utils/article_timer.py
Labels: finished

#62 #166000116 Fix parent info on the comments
  authors/apps/articles/models.py
  authors/apps/articles/tests/test_comments.py
  authors/apps/articles/utils.py
  authors/apps/articles/views.py
Labels: finished

#58 #165969268 Add ratings to an article
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_ratings.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/profiles/migrations/0001_initial.py
Labels: feedback implemented, reviews required

#66 #166027202 User can delete a specific notification
  authors/apps/appnotifications/tests/basetest.py
  authors/apps/appnotifications/tests/test_notifications.py
  authors/apps/appnotifications/urls.py
  authors/apps/appnotifications/views.py
  authors/settings.py
  authors/utils/notification_handlers.py
Labels: finished

#63 #165305771 Implement sharing of articles to various platforms
  authors/apps/articles/tests/test_social_share.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/utils/social_share_utils.py
  requirements.txt
Labels: finished

#71 #165914035 Add image support for articles CRUD
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_article_read_time.py
  authors/apps/articles/tests/test_articles.py
  authors/apps/articles/tests/test_tags.py
  authors/apps/articles/views.py
Labels: feedback implemented, reviews required

#68 #166028283 Fix email verification During signup
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/basetests.py
  authors/apps/authentication/tests/test_verify_user.py
  authors/apps/authentication/views.py
  authors/templates/mail.html
  authors/utils/authentication_handlers.py
Labels: reviews required

#73 #166062411 Add Image adjustment to readtime
  authors/apps/articles/tests/test_article_read_time.py
  authors/utils/article_timer.py
Labels: reviews required

#69 #165305773 User can report an article
  .gitignore
  authors/apps/appnotifications/migrations/0001_initial.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/escalation/__init__.py
  authors/apps/escalation/exceptions.py
  authors/apps/escalation/migrations/0001_initial.py
  authors/apps/escalation/migrations/__init__.py
  authors/apps/escalation/models.py
  authors/apps/escalation/serializers.py
  authors/apps/escalation/tests/__init__.py
  authors/apps/escalation/tests/basetest.py
  authors/apps/escalation/tests/test_escalation.py
  authors/apps/escalation/urls.py
  authors/apps/escalation/views.py
  authors/settings.py
  authors/urls.py
Labels: reviews required

#64 #165305775 Comments should be able to track edit history
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_comments.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
Labels: finished

#67 #165305774 Highlight Text and Comment on Articles
  README.md
  authors/apps/articles/migrations/0002_auto_20190516_2002.py
  authors/apps/highlights/__init__.py
  authors/apps/highlights/admin.py
  authors/apps/highlights/exceptions.py
  authors/apps/highlights/migrations/0001_initial.py
  authors/apps/highlights/migrations/0002_auto_20190516_0615.py
  authors/apps/highlights/migrations/0003_auto_20190516_1057.py
  authors/apps/highlights/migrations/__init__.py
  authors/apps/highlights/models.py
  authors/apps/highlights/serializers.py
  authors/apps/highlights/tests/__init__.py
  authors/apps/highlights/tests/basetests.py
  authors/apps/highlights/tests/test_highlights.py
  authors/apps/highlights/urls.py
  authors/apps/highlights/utils.py
  authors/apps/highlights/views.py
  authors/settings.py
  authors/urls.py
Labels: reviews required

#65 #165305772 Users can bookmark an article
  authors/apps/articles/exceptions.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0003_remove_article_bookmarkscount.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_bookmarks.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
Labels: finished

#59 #165305776 User should be able to like and dislike a comment
  authors/apps/articles/migrations/0002_auto_20190516_2002.py
  authors/apps/articles/migrations/0002_auto_20190518_1442.py
  authors/apps/articles/migrations/0003_remove_article_bookmarkscount.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/basetests.py
  authors/apps/articles/tests/test_comments.py
  authors/apps/articles/tests/test_like_comments.py
  authors/apps/articles/urls.py
  authors/apps/articles/utils.py
  authors/apps/articles/views.py
Labels: finished
